package Panel;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import ec.espe.edu.FoodAndRollOrderV.controller.PlateController;
import ec.espe.edu.FoodAndRollOrderV.controller.VoucherController;
import ec.espe.edu.FoodAndRollOrderV.model.Customer;
import ec.espe.edu.FoodAndRollOrderV.model.Plate;
import ec.espe.edu.FoodAndRollOrderV.model.ShoppingCart;
import ec.espe.edu.FoodAndRollOrderV.model.Voucher;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import static utils.DataBase.getCollection;
import utils.SettingId;

/**
 *
 * @author Mateo Gabriel Criollo/OOP14575/InterByte
 */
public class FrmCustomerOrder extends javax.swing.JFrame {

    public DefaultTableModel modelTablePlates;
    int quantity=0;
    
    private int id=0;
    private String description="";
    private double priceUnit=0;
    private int ivaPorcentage = 0;
    private double priceTotal;
    private String type="";
    
    private ArrayList<Plate> plates = new ArrayList<>();
    private Plate plate;
    
    private double subtotalGeneral=0.0;
    private double ivaGeneral=0.0;
    private double totalGeneral=0.0;
    
    private int auxIdDetail=1; //auxiliar
           
    private DefaultTableModel modelDataPLate;
    /**
     * Creates new form FrmCustomerOrder
     */
    public FrmCustomerOrder() {
        initComponents();
        this.UploadComboBox();
        this.inicializateTable();
        txtIva.setEnabled(false);
        txtTotal.setEnabled(false);
        txtSubtotal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrder = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txfNameCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfCellphoneNumber = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbPlate = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txfQuantity = new javax.swing.JTextField();
        btmAgreggate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSubtotal = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtIva = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTotal = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblOrder);

        jLabel2.setText("Nombre del Cliente: ");

        jLabel1.setText("Realizar Pedido");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Direccion");

        jLabel5.setText("Telefono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfNameCustomer))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCellphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCellphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setText("Plato:");

        cmbPlate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Cantidad: ");

        txfQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfQuantityKeyTyped(evt);
            }
        });

        btmAgreggate.setText("Anadir");
        btmAgreggate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAgreggateActionPerformed(evt);
            }
        });

        jLabel8.setText("Subtotal");

        jScrollPane2.setViewportView(txtSubtotal);

        jLabel9.setText("Iva:");

        jScrollPane3.setViewportView(txtIva);

        jLabel10.setText("Total");

        jScrollPane4.setViewportView(txtTotal);

        jButton1.setText("Hacer Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMenu1.setText("Customer");

        jMenu3.setText("Principal");
        jMenu1.add(jMenu3);

        jMenu4.setText("Home");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Realizar orden");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Consultar Orden");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btmAgreggate)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btmAgreggate))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmAgreggateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgreggateActionPerformed
        String combo = this.cmbPlate.getSelectedItem().toString();
        if(combo.equalsIgnoreCase("Seleccionar plato")){
            JOptionPane.showMessageDialog(null, "Seleccione un plato");
        }else{
            if(!txfQuantity.getText().isEmpty()){
                if(Integer.parseInt(txfQuantity.getText())>0){
                    
                    quantity = Integer.parseInt(txfQuantity.getText());
                    this.DataPlate();
                    plate = new Plate(id, description, (float) priceUnit, type, quantity, (float) priceTotal);
                    plates.add(plate);
                    JOptionPane.showMessageDialog(null, "Plato agregado");
                    this.UploadComboBox();
                    this.calculateTotal();
                }else{
                    JOptionPane.showMessageDialog(null, "La cantidad no puede ser cero");
                }
                    
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese la cantida del producto");
            }
        }
                this.EnterPlateOnTable();
    }//GEN-LAST:event_btmAgreggateActionPerformed

    public void calculateTotal(){
        subtotalGeneral=0;
        ivaGeneral = 0;
        totalGeneral=0;
        
        for(Plate foundPLate : plates){
            subtotalGeneral+=foundPLate.getPriceTotal();
        }
        
        ivaGeneral = subtotalGeneral*0.12;
        totalGeneral=subtotalGeneral+ivaGeneral;
        txtSubtotal.setText(String.valueOf(subtotalGeneral));
        txtIva.setText(String.valueOf(ivaGeneral));
        txtTotal.setText(String.valueOf(totalGeneral));
    }
    
    
    public void DataPlate(){
        MongoCollection <Document> collection = getCollection(PlateController.getNameCollection());
        FindIterable<Document> documents =collection.find(new Document("description",cmbPlate.getSelectedItem().toString()));
        MongoCursor <Document> cursor = documents.cursor();
        
        
        while(cursor.hasNext()){
            Document document = cursor.next();
            id=document.getInteger("id");
            description = document.getString("description");
            priceUnit = (document.getDouble("price"));
            priceTotal = priceUnit*quantity;
            type = document.getString("type");
            
         
        }
        
    }
    
    
    
    
    private void inicializateTable(){
        modelDataPLate = new DefaultTableModel();
        
        modelDataPLate.addColumn("Id");
        modelDataPLate.addColumn("Descripcion");
        modelDataPLate.addColumn("Tipo");
        modelDataPLate.addColumn("Precio U.");
        modelDataPLate.addColumn("Cantidad");
        modelDataPLate.addColumn("Precio T");
        modelDataPLate.addColumn("Accion");
        
        this.TblOrder.setModel(modelDataPLate);
    }
    
    
    
    public void EnterPlateOnTable(){
        this.modelDataPLate.setRowCount(plates.size());
        
        for(int i=0;i<plates.size();i++){
        this.modelDataPLate.setValueAt(i+1, i, 0);
        this.modelDataPLate.setValueAt(plates.get(i).getDescription(), i, 1);
        this.modelDataPLate.setValueAt(plates.get(i).getType(), i, 2);
        this.modelDataPLate.setValueAt(plates.get(i).getPrice(), i, 3);
        this.modelDataPLate.setValueAt(plates.get(i).getQuantity(), i, 4);
        this.modelDataPLate.setValueAt(plates.get(i).getPriceTotal(), i, 5);
        this.modelDataPLate.setValueAt("Eliminar", i, 6);
    }
        this.TblOrder.setModel(modelDataPLate);
    }
    
    
    private void txfQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfQuantityKeyTyped
        char caracter = evt.getKeyChar();
        
        if((caracter<'0'||caracter>'9')
                &&(caracter!=KeyEvent.VK_SPACE)
                ){
            evt.consume();
        }
    }//GEN-LAST:event_txfQuantityKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selection;
        selection = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de su orden ?","Logout",JOptionPane.YES_NO_OPTION);
        
        
        if (selection==JOptionPane.YES_OPTION){
            Customer customer = new Customer(txfCedula.getText(), txfNameCustomer.getText(), txfAddress.getText(), txfCellphoneNumber.getText());
            ShoppingCart shoppingCart = new ShoppingCart(SettingId.establishIdPlate(), plates, (float) subtotalGeneral);
            
            Voucher voucher = new Voucher(SettingId.establishIdPlate(), customer, shoppingCart, totalGeneral);
            if(VoucherController.createOrder(voucher)){
                empty();
            }else{
                
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void empty(){
        
        
    quantity=0;
    
    id=0;
    description="";
    priceUnit=0;
    ivaPorcentage = 0;
    priceTotal=0;
    type="";
    
    plates.clear();
    
     subtotalGeneral=0.0;
    ivaGeneral=0.0;
    totalGeneral=0.0;
    
    txfAddress.setText("");
    txfCedula.setText("");
    txfCellphoneNumber.setText("");
    txfNameCustomer.setText("");
    cmbPlate.setSelectedItem("Seleccionar plato");
    txfQuantity.setText("");
    
    
    txtIva.setText("");
    txtSubtotal.setText("");
    txtTotal.setText("");
        
            inicializateTable();
    }
    
    public void UploadComboBox(){
        
        MongoCollection <Document> collection = getCollection(PlateController.getNameCollection());
        FindIterable<Document> documents =collection.find();
        MongoCursor <Document> cursor = documents.iterator();
        
        cmbPlate.removeAllItems();
        cmbPlate.addItem("Seleccionar plato");
        
        while(cursor.hasNext()){
            
            Document document = cursor.next();
            cmbPlate.addItem(document.getString("description"));
        }
    }
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCustomerOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblOrder;
    private javax.swing.JButton btmAgreggate;
    private javax.swing.JComboBox<String> cmbPlate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfCedula;
    private javax.swing.JTextField txfCellphoneNumber;
    private javax.swing.JTextField txfNameCustomer;
    private javax.swing.JTextField txfQuantity;
    private javax.swing.JTextPane txtIva;
    private javax.swing.JTextPane txtSubtotal;
    private javax.swing.JTextPane txtTotal;
    // End of variables declaration//GEN-END:variables
}
